INSERT INTO DOCUMENT_TYPE VALUES('1','FONDO DE APERTURA');
INSERT INTO DOCUMENT_TYPE VALUES('3','FONDO DE CIERRE');
INSERT INTO DOCUMENT_TYPE VALUES('4','ANULACIÓN DE FONDO DE CIERRE');
INSERT INTO DOCUMENT_TYPE VALUES('724001','VENTA');
INSERT INTO DOCUMENT_TYPE VALUES('724003','DEVOLUCIÓN');
INSERT INTO DOCUMENT_TYPE VALUES('724009','TICKET MIXTO');
INSERT INTO DOCUMENT_TYPE VALUES('724005','FACTURA');
INSERT INTO DOCUMENT_TYPE VALUES('9','TICKET REGALO');
INSERT INTO DOCUMENT_TYPE VALUES('31','VENTA IPOD');
INSERT INTO DOCUMENT_TYPE VALUES('33','DEVOCLUCIÓN IPOD');
INSERT INTO DOCUMENT_TYPE VALUES('24','CANCELACIÓN ECOMMERCE');
INSERT INTO DOCUMENT_TYPE VALUES('15','DEVOLUCIÓN INTERNET');
INSERT INTO DOCUMENT_TYPE VALUES('724000','CANCELACIÓN');
INSERT INTO DOCUMENT_TYPE VALUES('724002','ANULACIÓN VENTA');
INSERT INTO DOCUMENT_TYPE VALUES('17','CANCELACIÓN OPERACIÓN ECOMMERCE');
INSERT INTO DOCUMENT_TYPE VALUES('16','CAMBIO INTERNET');
INSERT INTO DOCUMENT_TYPE VALUES('39','MOVIMIENTO DE RFID');


INSERT INTO PAYMENT_MEDIA VALUES('724001','EFECTIVO');
INSERT INTO PAYMENT_MEDIA VALUES('4','TARJETA ONLINE');
INSERT INTO PAYMENT_MEDIA VALUES('7','TARJETA ABONO');
INSERT INTO PAYMENT_MEDIA VALUES('10','TARJETA REGALO ECOMMERCE');
INSERT INTO PAYMENT_MEDIA VALUES('38','INWALLET AFFINITY');
INSERT INTO PAYMENT_MEDIA VALUES('6','TARJETA REGALO');
INSERT INTO PAYMENT_MEDIA VALUES('11','VALE ECOMMERCE');
INSERT INTO PAYMENT_MEDIA VALUES('724006','TARJETA AFFINITY');

INSERT INTO PRODUCT_TYPE VALUES(4, 'HOGAR');
INSERT INTO PRODUCT_TYPE VALUES(1, 'CALZADO Y BOLSOS');
INSERT INTO PRODUCT_TYPE VALUES(5, 'COMPRA TARJETA REGALO');
INSERT INTO PRODUCT_TYPE VALUES(2, 'PERFUMES');
INSERT INTO PRODUCT_TYPE VALUES(0, 'ROPA');
INSERT INTO PRODUCT_TYPE VALUES(9, 'ARREGLOS');
INSERT INTO PRODUCT_TYPE VALUES(29, 'BOLSAS');