INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('1','FONDO DE APERTURA');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('3','FONDO DE CIERRE');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('4','ANULACIÓN DE FONDO DE CIERRE');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('724001','VENTA');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('724003','DEVOLUCIÓN');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('724009','TICKET MIXTO');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('724005','FACTURA');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('9','TICKET REGALO');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('31','VENTA IPOD');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('33','DEVOCLUCIÓN IPOD');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('24','CANCELACIÓN ECOMMERCE');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('15','DEVOLUCIÓN INTERNET');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('724000','CANCELACIÓN');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('724002','ANULACIÓN VENTA');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('17','CANCELACIÓN OPERACIÓN ECOMMERCE');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('16','CAMBIO INTERNET');
INSERT IGNORE INTO DOCUMENT_TYPE VALUES ('39','MOVIMIENTO DE RFID');

INSERT IGNORE INTO PAYMENT_MEDIA VALUES ('724001','EFECTIVO');
INSERT IGNORE INTO PAYMENT_MEDIA VALUES ('4','TARJETA ONLINE');
INSERT IGNORE INTO PAYMENT_MEDIA VALUES ('7','TARJETA ABONO');
INSERT IGNORE INTO PAYMENT_MEDIA VALUES ('10','TARJETA REGALO ECOMMERCE');
INSERT IGNORE INTO PAYMENT_MEDIA VALUES ('38','INWALLET AFFINITY');
INSERT IGNORE INTO PAYMENT_MEDIA VALUES ('6','TARJETA REGALO');
INSERT IGNORE INTO PAYMENT_MEDIA VALUES ('11','VALE ECOMMERCE');
INSERT IGNORE INTO PAYMENT_MEDIA VALUES ('724006','TARJETA AFFINITY');

INSERT IGNORE INTO PRODUCT_TYPE VALUES (4, 'HOGAR');
INSERT IGNORE INTO PRODUCT_TYPE VALUES (1, 'CALZADO Y BOLSOS');
INSERT IGNORE INTO PRODUCT_TYPE VALUES (5, 'COMPRA TARJETA REGALO');
INSERT IGNORE INTO PRODUCT_TYPE VALUES (2, 'PERFUMES');
INSERT IGNORE INTO PRODUCT_TYPE VALUES (0, 'ROPA');
INSERT IGNORE INTO PRODUCT_TYPE VALUES (9, 'ARREGLOS');
INSERT IGNORE INTO PRODUCT_TYPE VALUES (29, 'BOLSAS');


